"""Initial migration - giao_hang_nhanh

Revision ID: d351deb0714c
Revises: 
Create Date: 2026-03-21 18:36:55.336151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd351deb0714c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('vai_tro', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tai_xe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bien_so', sa.String(length=20), nullable=True),
    sa.Column('loai_xe', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tong_don', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('thong_bao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('don_hang',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_don', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('tai_xe_id', sa.Integer(), nullable=True),
    sa.Column('dia_chi_lay', sa.String(length=255), nullable=False),
    sa.Column('dia_chi_giao', sa.String(length=255), nullable=False),
    sa.Column('loai_hang', sa.String(length=100), nullable=True),
    sa.Column('can_nang', sa.Float(), nullable=True),
    sa.Column('ghi_chu', sa.Text(), nullable=True),
    sa.Column('service_type', sa.String(length=20), nullable=True),
    sa.Column('gia_tien', sa.Float(), nullable=False),
    sa.Column('phi_dich_vu', sa.Float(), nullable=True),
    sa.Column('giam_gia', sa.Float(), nullable=True),
    sa.Column('tong_tien', sa.Float(), nullable=False),
    sa.Column('trang_thai', sa.String(length=30), nullable=True),
    sa.Column('ngay_tao', sa.DateTime(), nullable=True),
    sa.Column('ngay_duyet', sa.DateTime(), nullable=True),
    sa.Column('ngay_gan', sa.DateTime(), nullable=True),
    sa.Column('ngay_hoan_thanh', sa.DateTime(), nullable=True),
    sa.Column('ngay_huy', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tai_xe_id'], ['tai_xe.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ma_don')
    )
    op.create_table('danh_gia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('don_hang_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tai_xe_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['don_hang_id'], ['don_hang.id'], ),
    sa.ForeignKeyConstraint(['tai_xe_id'], ['tai_xe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thanh_toan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('don_hang_id', sa.Integer(), nullable=False),
    sa.Column('phuong_thuc', sa.String(length=50), nullable=False),
    sa.Column('so_tien', sa.Float(), nullable=False),
    sa.Column('trang_thai', sa.String(length=20), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('thoi_diem', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['don_hang_id'], ['don_hang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('don_hang_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thanh_toan')
    op.drop_table('danh_gia')
    op.drop_table('don_hang')
    op.drop_table('thong_bao')
    op.drop_table('tai_xe')
    op.drop_table('user')
    # ### end Alembic commands ###
